#!/bin/bash
# 快速创建测试数据
# 前提：已通过 Admin UI 创建管理员账号并导入 schema

echo "====================================="
echo "PocketBase 测试数据创建脚本"
echo "====================================="
echo ""
echo "请先完成以下步骤："
echo "1. 访问 http://127.0.0.1:8090/_/"
echo "2. 创建管理员账号（邮箱+密码）"
echo "3. 导入 pb_schema.json（Settings → Import collections）"
echo ""
echo "然后在 Admin UI 里手动添加测试数据："
echo ""
echo "Collection: center_news"
echo "-----------------------------------"
echo "示例记录 1:"
echo "  title: 齐鲁医学混合现实教学平台正式启用"
echo "  summary: 开启沉浸式医学教育新篇章"
echo "  body: 平台正式启用，支持多种教学场景。"
echo "  status: published"
echo "  publish_at: 2025-12-26"
echo ""
echo "示例记录 2（带图片占位符）:"
echo "  title: 3D打印中心完成首批精准解剖模型交付"
echo "  summary: 助力外科手术规划"
echo "  body: 首批模型已交付。{{img:1}}这是配图说明。"
echo "  status: published"
echo "  publish_at: 2025-12-20"
echo "  images: 上传1张图片"
echo ""
echo "====================================="
